/*
 * CrudSQL API
 *
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models CrudSQL provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taqi@mobix.biz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Schema information for a model field
    /// </summary>
    [DataContract(Name = "api.FieldSchema")]
    public partial class ApiFieldSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiFieldSchema" /> class.
        /// </summary>
        /// <param name="name">Name of the field.</param>
        /// <param name="operators">List of supported operators for this field.</param>
        /// <param name="type">Type of the field (e.g., string, int).</param>
        public ApiFieldSchema(string name = default(string), List<string> operators = default(List<string>), string type = default(string))
        {
            this.Name = name;
            this.Operators = operators;
            this.Type = type;
        }

        /// <summary>
        /// Name of the field
        /// </summary>
        /// <value>Name of the field</value>
        /*
        <example>ID</example>
        */
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// List of supported operators for this field
        /// </summary>
        /// <value>List of supported operators for this field</value>
        /*
        <example>[eq, neq, like]</example>
        */
        [DataMember(Name = "operators", EmitDefaultValue = false)]
        public List<string> Operators { get; set; }

        /// <summary>
        /// Type of the field (e.g., string, int)
        /// </summary>
        /// <value>Type of the field (e.g., string, int)</value>
        /*
        <example>string</example>
        */
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiFieldSchema {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Operators: ").Append(Operators).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
