/*
 * CrudSQL API
 *
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models CrudSQL provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taqi@mobix.biz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing DynamicApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DynamicApiTests : IDisposable
    {
        private DynamicApi instance;

        public DynamicApiTests()
        {
            instance = new DynamicApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DynamicApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DynamicApi
            //Assert.IsType<DynamicApi>(instance);
        }

        /// <summary>
        /// Test ModelFilterPost
        /// </summary>
        [Fact]
        public void ModelFilterPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string model = null;
            //QueryQueryFilter filter = null;
            //int? page = null;
            //int? pageSize = null;
            //string? sort = null;
            //var response = instance.ModelFilterPost(model, filter, page, pageSize, sort);
            //Assert.IsType<QueryFilterResponse>(response);
        }

        /// <summary>
        /// Test ModelGet
        /// </summary>
        [Fact]
        public void ModelGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string model = null;
            //int? page = null;
            //int? pageSize = null;
            //string? sort = null;
            //var response = instance.ModelGet(model, page, pageSize, sort);
            //Assert.IsType<QueryFilterResponse>(response);
        }

        /// <summary>
        /// Test ModelIdDelete
        /// </summary>
        [Fact]
        public void ModelIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string model = null;
            //string id = null;
            //var response = instance.ModelIdDelete(model, id);
            //Assert.IsType<ApiErrorResponse>(response);
        }

        /// <summary>
        /// Test ModelIdGet
        /// </summary>
        [Fact]
        public void ModelIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string model = null;
            //string id = null;
            //var response = instance.ModelIdGet(model, id);
            //Assert.IsType<QueryFilterResponse>(response);
        }

        /// <summary>
        /// Test ModelIdPut
        /// </summary>
        [Fact]
        public void ModelIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string model = null;
            //string id = null;
            //QueryEntityWithRelations entity = null;
            //var response = instance.ModelIdPut(model, id, entity);
            //Assert.IsType<QueryFilterResponse>(response);
        }

        /// <summary>
        /// Test ModelPost
        /// </summary>
        [Fact]
        public void ModelPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string model = null;
            //QueryEntityWithRelations entity = null;
            //var response = instance.ModelPost(model, entity);
            //Assert.IsType<QueryFilterResponse>(response);
        }
    }
}
