/*
 * CrudSQL API
 *
 * A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models CrudSQL provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger documentation - Multiple database support (SQL & NoSQL)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taqi@mobix.biz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ApiModelSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiModelSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiModelSchema
        //private ApiModelSchema instance;

        public ApiModelSchemaTests()
        {
            // TODO uncomment below to create an instance of ApiModelSchema
            //instance = new ApiModelSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiModelSchema
        /// </summary>
        [Fact]
        public void ApiModelSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiModelSchema
            //Assert.IsType<ApiModelSchema>(instance);
        }

        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Fact]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }

        /// <summary>
        /// Test the property 'Relationships'
        /// </summary>
        [Fact]
        public void RelationshipsTest()
        {
            // TODO unit test for the property 'Relationships'
        }
    }
}
